version: '2'
services:
    projeto_conteudo-app:
        image: projeto_conteudo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://projeto_conteudo-mysql:3306/projeto_conteudo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    projeto_conteudo-mysql:
        extends:
            file: mysql.yml
            service: projeto_conteudo-mysql
